# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=50, verbose_name='Package Name')),
                ('packageCost', models.CharField(max_length=10, verbose_name='Package Cost')),
                ('packageDescription', models.TextField(max_length=1000, verbose_name='Package Description')),
                ('packagePhotos', models.ImageField(upload_to='images/', verbose_name='Photos to Upload')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('locationDescription', models.TextField(max_length=1000, verbose_name='Location Description')),
                ('locationPhotos', models.ImageField(upload_to='images/', verbose_name='Photos to Upload')),
                ('noOfDays', models.IntegerField(verbose_name='No. of days')),
                ('noOfNights', models.IntegerField(verbose_name='No. of nights')),
            ],
        ),
    ]
