# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='locationPhotos',
            field=models.ImageField(max_length=255, upload_to='images/', verbose_name='Photos to Upload'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='packagePhotos',
            field=models.ImageField(max_length=255, upload_to='images/', verbose_name='Photos to Upload'),
        ),
    ]
