# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobileNumber',
            field=models.CharField(default=0, max_length=10, verbose_name=b'Mobile Number'),
            preserve_default=False,
        ),
    ]
