# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mobileNumber',
        ),
    ]
