# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171115_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobileNumber',
            field=models.CharField(max_length=10, verbose_name=b'Mobile Number'),
        ),
    ]
