# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accomodationStarCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodationStar', models.CharField(max_length=50, verbose_name='Accomodation in Star Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='accomodationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodationStar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodation_Star', to='marketing.accomodationStarCreation', verbose_name='Accomodation in Star hotel')),
            ],
        ),
        migrations.CreateModel(
            name='accomodationTypeCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodationType', models.CharField(max_length=50, verbose_name='Accomodation Type')),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=50, verbose_name='Package Name')),
                ('contactAddress', models.TextField(max_length=200, verbose_name='Contact Address')),
                ('contactMobile', models.CharField(max_length=50, verbose_name='Mobile')),
                ('contactMail', models.EmailField(max_length=50, verbose_name='Email')),
                ('dateDeparture', models.DateField(verbose_name='Date of Departure')),
                ('dateArrival', models.DateField(verbose_name='Date of Arrival')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('totalPersons', models.IntegerField(verbose_name='Total number of persons')),
                ('adultPersons', models.IntegerField(verbose_name='No. of adults')),
                ('childPersons', models.IntegerField(verbose_name='No. of Children')),
                ('infantPersons', models.IntegerField(verbose_name='No. of infants')),
                ('breakfast', models.BooleanField(verbose_name='Breakfast included')),
                ('lunch', models.BooleanField(verbose_name='Lunch included')),
                ('dinner', models.BooleanField(verbose_name='Dinner included')),
                ('notes', models.TextField(verbose_name='Notes, if any')),
            ],
        ),
        migrations.AddField(
            model_name='accomodationtype',
            name='accomodationType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accomodationType_marketing', to='marketing.accomodationTypeCreation', verbose_name='Accomodation Type'),
        ),
        migrations.AddField(
            model_name='accomodationtype',
            name='marketing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Marketing_accomodationtype', to='marketing.Marketing'),
        ),
    ]
