# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=50, verbose_name='Package Name')),
                ('contactAddress', models.TextField(max_length=200, verbose_name='Contact Address')),
                ('contactMobile', models.CharField(max_length=50, verbose_name='Mobile')),
                ('contactMail', models.EmailField(max_length=50, verbose_name='Email')),
                ('dateDeparture', models.DateField(verbose_name='Date of Departure')),
                ('dateArrival', models.DateField(verbose_name='Date of Arrival')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('totalPersons', models.IntegerField(verbose_name='Total number of persons')),
                ('adultPersons', models.IntegerField(verbose_name='No. of adults')),
                ('childPersons', models.IntegerField(verbose_name='No. of Children')),
                ('infantPersons', models.IntegerField(verbose_name='No. of infants')),
                ('accomodationType', models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort')], max_length=50, verbose_name='Accomodation type')),
                ('accomodationStar', models.CharField(choices=[('2 Star', '2'), ('3 Star', '3'), ('4 Star', '4'), ('5 Star', '5')], max_length=50, verbose_name='Accomodation in Star Hotel')),
                ('modeOfTransport', models.CharField(choices=[('FLIGHT', 'FLIGHT'), ('TRAIN', 'TRAIN'), ('BUS', 'BUS'), ('CAR', 'CAR'), ('GROUP', 'GROUP')], max_length=50, verbose_name='Mode of Transport')),
                ('transportType', models.CharField(choices=[('ECONOMY', 'ECONOY'), ('BUSINESS CLASS', 'BUSINESS CLASS')], max_length=50, verbose_name='Type of transport')),
                ('breakfast', models.BooleanField(verbose_name='Breakfast included')),
                ('lunch', models.BooleanField(verbose_name='Lunch included')),
                ('dinner', models.BooleanField(verbose_name='Dinner included')),
                ('notes', models.TextField(verbose_name='Notes, if any')),
            ],
        ),
    ]
