# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationtype',
            name='marketing_id',
        ),
        migrations.AddField(
            model_name='marketing',
            name='accomodation',
            field=models.ManyToManyField(to='marketing.accomodationType'),
        ),
    ]
