# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='transportType',
        ),
        migrations.AlterField(
            model_name='marketing',
            name='modeOfTransport',
            field=models.CharField(choices=[('FLIGHT', (('ECONOMY', 'ECONOMY'), ('BUSINESS CLASS', 'BUSINESS CLASS'))), ('TRAIN', (('AC', 'AC'), ('NON AC', 'NON AC'))), ('BUS', (('SLEEPER', 'SLEEPER'), ('SEMI-SLEEPER', 'SEMI-SLEEPER'))), ('CAR', (('INDIGO', 'INDIGO'), ('INNOVA', 'INNOVA'), ('TEMPO', 'TEMPO'))), ('GROUP', (('MINI BUS', 'MINI BUS'), ('BUS', 'BUS')))], max_length=50, verbose_name='Mode of Transport'),
        ),
    ]
