# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20171113_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourPackage',
            new_name='Marketing',
        ),
    ]
